### ISSUE TITLE
unable to compile HEAD

### ISSUE THREAD

**Issue by macromachine** [libyal/liblnk#34]
Hi,
the lastest version cannot be compiled.
The error information:

```
gcc: error: @LIBCERROR_DLL_EXPORT@: No such file or directory
Makefile:620: recipe for target 'libcerror_error.lo' failed
make[1]: *** [libcerror_error.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common @LIBCERROR_DLL_EXPORT@ -g -O2 -Wall -MT libcerror_system.lo -MD -MP -MF .deps/libcerror_system.Tpo -c libcerror_system.c  -fPIC -DPIC -o .libs/libcerror_system.o
gcc: error: @LIBCERROR_DLL_EXPORT@: No such file or directory
Makefile:620: recipe for target 'libcerror_system.lo' failed
make[1]: *** [libcerror_system.lo] Error 1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common @LIBCERROR_DLL_EXPORT@ -g -O2 -Wall -MT libcerror_support.lo -MD -MP -MF .deps/libcerror_support.Tpo -c libcerror_support.c  -fPIC -DPIC -o .libs/libcerror_support.o
gcc: error: @LIBCERROR_DLL_EXPORT@: No such file or directory
Makefile:620: recipe for target 'libcerror_support.lo' failed
make[1]: *** [libcerror_support.lo] Error 1
make[1]: Leaving directory '/home/hjwang/Fuzz_Experiment/liblnk-fast/libcerror'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by joachimmetz** [comment]
Yes this is a known issue when tying to compile from head. First of all this project recommend not to compile from HEAD unless you are active developing the project. https://github.com/libyal/liblnk/wiki/Building#read-first

**Comment by macromachine** [comment]
Thanks for the reply.
I'd like to use the history version to reproduce some problems.
Is there any solution for this purpose? Thanks a lot.

**Comment by joachimmetz** [comment]
Issue address in https://github.com/libyal/liblnk/commit/c0995fe4efd689a49ea302212edc1bd764b1fb94

> I'd like to use the history version to reproduce some problems.

It is unclear you me what you mean with this? If you want a previous pre-release use the available releases otherwise the version in git is work in progress / under development they are not considered releases by this project, but mere commits.
