### ISSUE TITLE
liblnk liblnk_file_get_show_window_value() fetches file size not window value

### ISSUE THREAD

**Issue by liamjm** [libyal/liblnk#43]
https://github.com/libyal/liblnk/blob/71a5ed8b560fb45be94cbb552cc05a4738a23207/liblnk/liblnk_file.c#L2626

"""
*show_window_value = internal_file->file_information->size;
"""
Also the same in liblnk_file_get_hot_key_value

**Comment by joachimmetz** [comment]
@liamjm thx for flagging

**Comment by joachimmetz** [comment]
Proposed changes https://github.com/libyal/liblnk/pull/44 merged
