### ISSUE TITLE
lnkinfo: string in metadata property store data block is not shown

### ISSUE THREAD

**Issue by eabase** [libyal/liblnk#47]
Hello, 
I've found that links also contain a field telling where they were first created.

For example, here are 2 nearly equivalent powershell (core) links. One was copied and made to use new path, from an earlier version and the other was automatically created by powershell installer. Although, `lnkinfo.exe` does not detect any difference apart the timestamps, there is considerable difference in file structure and content (only visible with hexedit), ~40 bytes.

```bash
$ \ls -lH pwsh*
-rwxr-xrwx+ 1 xxxx None 1650 Dec 22 06:11 pwsh7.lnk
-rwxr-xrwx+ 1 xxxx None 1610 Dec 22 06:11 pwsh8.lnk

# strings -a -t x -e l -n3 pwsh7.lnk
     c1 Program Files
     dd @shell32.dll,-21781
    14d PowerShell
    1a9 w7-preview
    207 pwsh.exe
    27a %C:\Program Files\PowerShell\7-preview
    2f7 7-preview (C:\Program Files\PowerShell\7)
    378 S-1-5-21-834826149-1087668994-4147927960-1001
    401 pwsh.exe
    450 Application
    4aa C:\Program Files\PowerShell\7\7-preview\pwsh.exe         # <----  HIDDEN
    5ce Lucida Console

$ strings -a -t x -e l -n3 pwsh8.lnk
     bf TProgram Files
     dd @shell32.dll,-21781
    14b 1PowerShell
    1ab 7-preview
    207 pwsh.exe
    27a %C:\Program Files\PowerShell\7-preview
    2f7 6 (C:\Program Files\PowerShell)
    364 S-1-5-21-834826149-1087668994-4147927960-1001
    3ed pwsh.exe
    43c Application
    496 C:\Program Files\PowerShell\6\pwsh.exe         # <----  HIDDEN
    5a6 Lucida Console

```

and not seen using this tool:

```bash
# lnkinfo.exe pwsh7.lnk |head -22
lnkinfo 20201129

Windows Shortcut information:
 Contains a link target identifier
 Contains a working directory string

Link information:
 Creation time        : Apr 21, 2020 16:14:04.000000000 UTC
 Modification time     : Apr 21, 2020 16:14:04.000000000 UTC
 Access time    : Apr 29, 2020 16:47:57.799955900 UTC
 File size     : 297552 bytes
 Icon index     : 0
 Show Window value     : 0x00000001
 Hot Key value        : 0
 File attribute flags  : 0x00000020
    Should be archived (FILE_ATTRIBUTE_ARCHIVE)
 Drive type     : Fixed (3)
 Drive serial number   : 0xf7f187d0
 Volume label         :
 Local path     : C:\Program Files\PowerShell\7-preview\pwsh.exe
 Working directory     : C:\Program Files\PowerShell\7-preview
...

# lnkinfo.exe pwsh8.lnk |head -22
lnkinfo 20201129

Windows Shortcut information:
 Contains a link target identifier
 Contains a working directory string

Link information:
 Creation time        : Dec 14, 2020 21:05:34.000000000 UTC
 Modification time     : Dec 14, 2020 21:05:34.000000000 UTC
 Access time    : Dec 21, 2020 21:10:12.191710900 UTC
 File size     : 274312 bytes
 Icon index     : 0
 Show Window value     : 0x00000001
 Hot Key value        : 0
 File attribute flags  : 0x00000020
    Should be archived (FILE_ATTRIBUTE_ARCHIVE)
 Drive type     : Fixed (3)
 Drive serial number   : 0xf7f187d0
 Volume label         :
 Local path     : C:\Program Files\PowerShell\7-preview\pwsh.exe
 Working directory     : C:\Program Files\PowerShell\7-preview
...
```

**Comment by joachimmetz** [comment]
Can you share your test files? Otherwise I cannot determine what you are talking about

**Comment by eabase** [comment]
You can easily reproduce this, by instally (any) powershell (core) [release](https://github.com/PowerShell/PowerShell/releases). It will create a soft link on desktop. You may surely also already have some shell link on your desktop, so inspect any of them. 

It beoce more apparent when you copy one link and change it to point somewhere else using Win GUI, then you will find that part of the original (a path?) is still hidden within the file.

**Comment by eabase** [comment]
PS. I see you changed the issue title, to something that now doesn't make any sense. Please explain.

**Comment by joachimmetz** [comment]
> to something that now doesn't make any sense. Please explain.

That is because I have a hard time figuring out what you mean. You provide very little context. Just output of files and claim to a 40 byte difference without the details.

Can you just share the test files, that will make determining what you mean and resolving this issue much easier.

**Comment by eabase** [comment]
I reported a new powershell issue here:
* https://github.com/PowerShell/PowerShell/issues/14482

I created a symlink using powershell core (pwsh.exe), but `lnkinfo.exe` is not able to handle these new links:
```powershell

$ New-Item -ItemType SymbolicLink -Path C:\Users\xxxx\Desktop\pwss -Target "C:\Program Files\PowerShell\7-preview\pwsh.exe"

$ Get-ChildItem C:\Users\xxxx\Desktop\pwss | fl

    Directory: C:\Users\xxxx\Desktop

Name           : pwss
Length         : 0
CreationTime   : 2020-12-22 19:54:21
LastWriteTime  : 2020-12-22 19:54:21
LastAccessTime : 2020-12-22 19:54:21
Mode           : -a---l
LinkType       : SymbolicLink
Target         : {C:\Program Files\PowerShell\7-preview\pwsh.exe}
VersionInfo    : File:             C:\Users\xxxx\Desktop\pwss
                 InternalName:     pwsh.dll
                 OriginalFilename: pwsh.dll
                 FileVersion:      7.2.0.0
                 FileDescription:  pwsh
                 Product:          PowerShell
                 ProductVersion:   7.2.0-preview.2 SHA: 47ef533b2edd5f4cfae5adb9533613f142dc4315
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:         Language Neutral


$ lnkinfo.exe pwss
lnkinfo 20201129

Unable to open: pwss.
liblnk_file_header_read_data: unsupported header size: 9460301.
liblnk_file_header_read_file_io_handle: unable to read file header.
liblnk_internal_file_open_read: unable to read file header.
liblnk_file_open_file_io_handle: unable to read from file IO handle.
liblnk_file_open: unable to open file: pwss.
info_handle_open_input: unable to open input file.
```

This is weird, as it look more like hard link...

**Comment by eabase** [comment]
> Can you just share the test files, that will make determining what you mean and resolving this issue much easier.
Sure: [here](http://www.filedropper.com/links_3)

**Comment by eabase** [comment]
I was just informed that these "links" are "shortcuts" and not *symlinks*. IDK what the implication of this is. I was always under the impression that these thing were the same.

**Comment by joachimmetz** [comment]
so both pwsh_ok.lnk and pwsh_bad.lnk  work fine for me, regarding the "hidden string"

```
lnkinfo links/pwsh_ok.lnk 
lnkinfo 20201222

Windows Shortcut information:
	Contains a link target identifier
	Contains a working directory string

Link information:
	Creation time			: Dec 14, 2020 21:05:34.000000000 UTC
	Modification time		: Dec 14, 2020 21:05:34.000000000 UTC
	Access time			: Dec 21, 2020 21:10:12.191710900 UTC
	File size			: 274312 bytes
	Icon index			: 0
	Show Window value		: 0x00000001
	Hot Key value			: 0
	File attribute flags		: 0x00000020
		Should be archived (FILE_ATTRIBUTE_ARCHIVE)
	Drive type			: Fixed (3)
	Drive serial number		: 0xf7f187d0
	Volume label			: 
	Local path			: C:\Program Files\PowerShell\7-preview\pwsh.exe
	Working directory		: C:\Program Files\PowerShell\7-preview

Link target identifier:
	Shell item list
		Number of items		: 6

	Shell item: 1
		Item type		: Root folder
		Class type indicator	: 0x1f (Root folder)
		Shell folder identifier	: 20d04fe0-3aea-1069-a2d8-08002b30309d
		Shell folder name	: My Computer

	Shell item: 2
		Item type		: Volume
		Class type indicator	: 0x2f (Volume)
		Volume name		: C:\

	Shell item: 3
		Item type		: File entry
		Class type indicator	: 0x31 (File entry: Directory)
		Name			: PROGRA~1
		Modification time	: Dec 15, 2020 17:12:34
		File attribute flags	: 0x00000011
			Is read-only (FILE_ATTRIBUTE_READ_ONLY)
			Is directory (FILE_ATTRIBUTE_DIRECTORY)
	Extension block: 1
		Signature		: 0xbeef0004 (File entry extension)
		Long name		: Program Files
		Localized name		: @shell32.dll,-21781
		Creation time		: Aug 22, 2013 13:36:16
		Access time		: Dec 15, 2020 17:12:34
		NTFS file reference	: MFT entry: 67, sequence: 1

	Shell item: 4
		Item type		: File entry
		Class type indicator	: 0x31 (File entry: Directory)
		Name			: POWERS~1
		Modification time	: Dec 21, 2020 21:10:12
		File attribute flags	: 0x00000010
			Is directory (FILE_ATTRIBUTE_DIRECTORY)
	Extension block: 1
		Signature		: 0xbeef0004 (File entry extension)
		Long name		: PowerShell
		Creation time		: Dec 04, 2018 03:17:58
		Access time		: Dec 21, 2020 21:10:12
		NTFS file reference	: MFT entry: 174307, sequence: 3

	Shell item: 5
		Item type		: File entry
		Class type indicator	: 0x31 (File entry: Directory)
		Name			: 7-PREV~1
		Modification time	: Dec 21, 2020 21:10:16
		File attribute flags	: 0x00000010
			Is directory (FILE_ATTRIBUTE_DIRECTORY)
	Extension block: 1
		Signature		: 0xbeef0004 (File entry extension)
		Long name		: 7-preview
		Creation time		: Dec 21, 2020 21:10:12
		Access time		: Dec 21, 2020 21:10:16
		NTFS file reference	: MFT entry: 349419, sequence: 84

	Shell item: 6
		Item type		: File entry
		Class type indicator	: 0x32 (File entry: File)
		Name			: pwsh.exe
		Modification time	: Dec 14, 2020 21:05:34
		File attribute flags	: 0x00000020
			Should be archived (FILE_ATTRIBUTE_ARCHIVE)
	Extension block: 1
		Signature		: 0xbeef0004 (File entry extension)
		Long name		: pwsh.exe
		Creation time		: Dec 14, 2020 21:05:34
		Access time		: Dec 21, 2020 21:10:14
		NTFS file reference	: MFT entry: 544598, sequence: 520



Distributed link tracking data:
	Machine identifier		: xxxx
	Droid volume identifier		: f1835460-c106-498f-beb2-b73a5006b302
	Droid file identifier		: bc482e1b-42db-11eb-834b-7824af1db24c
	Birth droid volume identifier	: f1835460-c106-498f-beb2-b73a5006b302
	Birth droid file identifier	: bc482e1b-42db-11eb-834b-7824af1db24c
```

Your additional string is stored in the metadata property store data block which is currently not shown by lnkinfo.

```
Reading metadata property store data block:
libfwps_storage_copy_from_byte_stream: size                             : 109
libfwps_storage_copy_from_byte_stream: signature                        : 1SPS
libfwps_storage_copy_from_byte_stream: format class identifier          : {DABD30ED-0043-4789-A7F8-D013A4736622}
libfwps_value_copy_from_byte_stream: property value data:
00000000: 51 00 00 00 64 00 00 00  00 1f 00 00 00 20 00 00   Q...d... ..... ..
00000010: 00 36 00 20 00 28 00 43  00 3a 00 5c 00 50 00 72   .6. .(.C .:.\.P.r
00000020: 00 6f 00 67 00 72 00 61  00 6d 00 20 00 46 00 69   .o.g.r.a .m. .F.i
00000030: 00 6c 00 65 00 73 00 5c  00 50 00 6f 00 77 00 65   .l.e.s.\ .P.o.w.e
00000040: 00 72 00 53 00 68 00 65  00 6c 00 6c 00 29 00 00   .r.S.h.e .l.l.)..
00000050: 00                                                 .
```

**Comment by joachimmetz** [comment]
> I was just informed that these "links" are "shortcuts" and not symlinks. IDK what the implication of this is. I was always under the impression that these thing were the same.

Nope, tl;dr lnk/shortcuts are "Shell links" (explorer.exe or Windows Shell), symlinks are file system-level indirect references to other files, and hardlinks are system-level different names/paths for the same file.

**Comment by eabase** [comment]
Yeah, the `god` vs `bad` thing, is a different (primarily on W81) issue of interfering with powershell core... 

Some other shortcut info:
* http://powershellblogger.com/2016/01/create-shortcuts-lnk-or-url-files-with-powershell/
* https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_shortcut.ps1

Any idea what is the purpose of this *metadata* and if it is used/processed somewhere?
I suspect it is exactly this that is causing this other mysterious terminal bug...

**Comment by eabase** [comment]
> Your additional string is stored in the metadata property store data block which is currently not shown by lnkinfo.

ok, so what were you using above, to read it?

**Comment by joachimmetz** [comment]
> ok, so what were you using above, to read it?

debug output mode of liblnk, see: https://github.com/libyal/liblnk/wiki/Troubleshooting#verbose-and-debug-output

**Comment by eabase** [comment]
Thanks a lot Joachim, 
I really appreciate your time to check and explain this. :100: 


BTW. I am not able to get the debug output. I used this config. 

```bash
CPPCFLAGS=-g ./configure --enable-shared=no --enable-static-executables=yes --enable-verbose-output --enable-debug-output
```

**Comment by joachimmetz** [comment]
> Eehr, did you just make a PR commit for this?

nope, the recent commit is some clean up, debug-output has been in there from the start to help debug the format

Try:
```
./configure --enable-verbose-output --enable-debug-output && make clean && make
./lnktools/liblnk -v file.lnk
```

**Comment by joachimmetz** [comment]
> Any idea what is the purpose of this metadata and if it is used/processed somewhere?

To contain some metadata:
* https://github.com/libyal/liblnk/blob/main/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#68-the-metadata-property-store-data-block
* https://github.com/libyal/libfwps/blob/main/documentation/Windows%20Property%20Store%20format.asciidoc

Looks like category/class `DABD30ED-0043-4789-A7F8-D013A4736622` is used for System.ItemFolderPathDisplayNarrow: https://docs.microsoft.com/en-us/windows/win32/properties/props-system-itemfolderpathdisplaynarrow

**Comment by eabase** [comment]
^^ That worked. Funny why the previous and longer `./configure` didn't work...

I think I have found a solution to my (external) issue. It's something to do with the parsing of the console color properties within the terminal (contained in the metadata property store data block). 

* https://github.com/libyal/liblnk/blob/main/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#6-extra-data

Probably in this part: 
* https://github.com/libyal/liblnk/blob/main/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#621-console-color-flags

Do you have any idea how we can parse this? I was hoping to see some FOSS tool similar to [010 Editr](https://www.sweetscape.com/010editor/) where you can define and save structures.

**Comment by eabase** [comment]
Yes, found some binary editor options (as I see you are well aware of):

* https://github.com/kaitai-io/awesome-kaitai
* https://github.com/Vector35/kaitai
* https://codisec.com/veles/  (seem like a dead project??)

Anyway, everything is understood now, so feel free to close this. 

The 4 bytes above, correspond to: 
```bash
# HKCU:\Console\<symlink_path>
97      -->     17      - ScreenColors  : 23
01      -->     00      - ColorTable01  : "2nd color box from the left"
24 54   -->     00 ff   - ColorTable09  : "10th color box from the left"
```

**Comment by joachimmetz** [comment]
> Anyway, everything is understood now, so feel free to close this.

ack, good to hear, closing issue
