### ISSUE TITLE
Support for property streams and SIDs

### ISSUE THREAD

**Issue by wxsBSD** [libyal/liblnk#48]
The LNK file mentioned in https://unit42.paloaltonetworks.com/cloaked-ursa-online-storage-services-campaigns/ has a property stream which represents the SID of the account that created the LNK. Is it possible to extend liblnk to handle these property streams (there are many of them, beyond just the SID one)?

**Comment by joachimmetz** [comment]
I'll have a look, I'll likely have liblnk just return the data like with shell items and have libfwps handle the property sheets

**Comment by joachimmetz** [comment]
Support for metadata property store data blocks has been added. Closing issue.
